services:
  springboot-app:
    build: .
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/economy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12341234
    ports:
      - "8080:8080"
