version: '3'
services:
  springboot-app:
    build: .
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/economy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12341234
    ports:
      - "8080:8080"
#    depends_on:
#      - db

#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - springboot-app

#  db:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: economy
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 12341234
#    ports:
#      - "5432:5432"