create table info
(
    id          integer generated by default as identity
        primary key,
    name        varchar(100) not null
        unique,
    description text
);

create table dow
(
    id                integer generated by default as identity
        primary key,
    date              date             not null,
    open_price        double precision not null,
    close_price       double precision not null,
    high_price        double precision not null,
    low_price         double precision not null,
    volume            bigint           not null,
    change_percentage double precision not null
);
create table nasdaq100
(
    id                integer generated by default as identity
        primary key,
    date              date             not null,
    open_price        double precision not null,
    close_price       double precision not null,
    high_price        double precision not null,
    low_price         double precision not null,
    volume            bigint           not null,
    change_percentage double precision not null
);
create table russell2000
(
    id                integer generated by default as identity
        primary key,
    date              date             not null,
    open_price        double precision not null,
    close_price       double precision not null,
    high_price        double precision not null,
    low_price         double precision not null,
    volume            bigint           not null,
    change_percentage double precision not null
);
create table sp500
(
    id                integer generated by default as identity
        primary key,
    date              date             not null,
    open_price        double precision not null,
    close_price       double precision not null,
    high_price        double precision not null,
    low_price         double precision not null,
    volume            bigint           not null,
    change_percentage double precision not null
);

create table treasury_2yr
(
    id                integer generated by default as identity
        primary key,
    date              date             not null,
    open_price        double precision not null,
    close_price       double precision not null,
    high_price        double precision not null,
    low_price         double precision not null,
    volume            bigint           not null,
    change_percentage double precision not null
);

create table treasury_10yr
(
    id                integer generated by default as identity
        primary key,
    date              date             not null,
    open_price        double precision not null,
    close_price       double precision not null,
    high_price        double precision not null,
    low_price         double precision not null,
    volume            bigint           not null,
    change_percentage double precision not null
);

create table dollar
(
    id                integer generated by default as identity
        primary key,
    date              date             not null,
    open_price        double precision not null,
    close_price       double precision not null,
    high_price        double precision not null,
    low_price         double precision not null,
    volume            bigint           not null,
    change_percentage double precision not null
);

create table gold
(
    id                integer generated by default as identity
        primary key,
    date              date             not null,
    open_price        double precision not null,
    close_price       double precision not null,
    high_price        double precision not null,
    low_price         double precision not null,
    volume            bigint           not null,
    change_percentage double precision not null
);

create table wti_oil
(
    id                integer generated by default as identity
        primary key,
    date              date             not null,
    open_price        double precision not null,
    close_price       double precision not null,
    high_price        double precision not null,
    low_price         double precision not null,
    volume            bigint           not null,
    change_percentage double precision not null
);

create table natural_gas
(
    id                integer generated by default as identity
        primary key,
    date              date             not null,
    open_price        double precision not null,
    close_price       double precision not null,
    high_price        double precision not null,
    low_price         double precision not null,
    volume            bigint           not null,
    change_percentage double precision not null
);

create table economic_indicators
(
    id              serial
        primary key,
    event_type      varchar(50),
    indicator_name  varchar(255),
    fed_speaker     varchar(100),
    fed_position    varchar(100),
    event_date      date,
    event_time_kst  timestamp,
    event_time_est  timestamp,
    indicator_value varchar(50),
    forecast_value  varchar(50),
    previous_value  varchar(50),
    content         text,
    importance      integer
);