
logging:
  level:
    hello.boilerplate: debug

spring:
  application:
    name:boilerplate
  datasource:
    url: jdbc:postgresql://localhost:5432/economy
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12341234

  jpa:
    hibernate:
      dd-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
    open-in-view: false